name: notigram
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  share: ^0.6.2
  dotted_border: ^1.0.2
  mailer: ^3.0.2
  cloud_functions: ^0.4.1
  flutter_screenutil: ^0.5.3
  cached_network_image: ^2.0.0-rc #^1.1.1
  #  base_module:
  #    path: /Users/ghost/desktop/base_module
  firebase_dynamic_links: ^0.5.0+6
  cloud_firestore: ^0.12.9+6
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.6

  photo_view: ^0.4.0
  country_pickers: ^1.0.2
  flutter_datetime_picker: 1.2.1
  flutter_simple_video_player:
  connectivity: ^0.4.3+6
  connectivity_widget: ^0.1.0+1
  tripledes: ^2.1.0
  webview_flutter: ^0.3.15+1
  photo_manager: ^0.4.3
  uuid: 2.0.0
  url_launcher: ^5.2.5
  date_format: ^1.0.6
  flutter_device_type: ^0.2.0
  smart_text_view: ^0.1.0
  image_cropper: ^1.1.0
  thumbnails: ^1.0.1
  timeago: ^2.0.10
  video_thumbnail: ^0.1.5+1
  device_info: ^0.4.1+1
  flutter_masked_text:
  pin_code_view:
  image_picker:
  # Use device_apps or flutter availability for installed app detection
  # device_apps: ^1.0.9 
  # flutter_appavailability: ^0.0.21

  flutter_swiper : any
  shared_preferences: any
  fancy_on_boarding: ^1.4.0
  flutter_login: ^1.0.14
  # animated_splash: ^1.0.0
  bottom_navy_bar: ^5.3.2
  # expandable_bottom_sheet: ^0.2.1+1
  # popup_menu: ^1.0.5
  super_tooltip: ^0.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  
flutter_icons:	
  android: true	
  ios: true	
  image_path: "assets/notigram.png" #run in terminal; flutter pub pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:

  fonts:
    - family: Poppin
      fonts:
        - asset: assets/Poppins-SemiBold.ttf
        - asset: assets/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
